sudo: required
language: cpp

matrix:
  include:
    - os: linux
      dist: xenial
    - os: osx
      osx_image: xcode11.3


compiler:
  - gcc

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then uname -a; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then echo uname -a; sudo sh scripts/.travis-bootstrap-ubuntu.sh; fi

script:
  - sh scripts/buildAndRunTests.sh

